defaults:
 # base trident datamodule configuration
 - trident

dataloader_cfg:
  train:
    batch_size: 8

dataset_cfg:
  _method_: # get methods of _target_ object
    map: # dataset.map -> tokenization
      # kwargs for dataset.map
      function:
        _target_: trident.utils.hydra.partial
        _partial_: src.tasks.text_classification.processor.preprocess_fn
        column_names:
          text: premise
          text_pair: hypothesis
    # unify output format of MNLI and XNLI
    set_format:
      columns:
        - "input_ids"
        - "attention_mask"
        - "label"
  train:
    _datasets_:
      en:
        path: glue
        name: mnli
        split: train
      aym:
        path: americas_nli
        name: aym
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 0
                - ${shots}
      bzd:
        path: americas_nli
        name: bzd
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 0
                - ${shots}
      gn:
        path: americas_nli
        name: gn
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 0
                - ${shots}
      quy:
        path: americas_nli
        name: quy
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 0
                - ${shots}
      tar:
        path: americas_nli
        name: tar
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 0
                - ${shots}
      shp:
        path: americas_nli
        name: shp
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 0
                - ${shots}
      hch:
        path: americas_nli
        name: hch
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 0
                - ${shots}
  val:
    # Huggingface datasets syntax to concatenate these splits
    _datasets_:
      validation_anli_aym:
        path: americas_nli
        name: aym
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 500
                - 742
      test_anli_aym:
        path: americas_nli
        name: aym
        split: test
      validation_anli_quy:
        path: americas_nli
        name: quy
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 500
                - 742
      test_anli_quy:
        path: americas_nli
        name: quy
        split: test
      validation_anli_shp:
        path: americas_nli
        name: shp
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 500
                - 742
      test_anli_shp:
        path: americas_nli
        name: shp
        split: test
      validation_anli_tar:
        path: americas_nli
        name: tar
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 500
                - 742
      test_anli_tar:
        path: americas_nli
        name: tar
        split: test
      validation_anli_gn:
        path: americas_nli
        name: gn
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 500
                - 742
      test_anli_gn:
        path: americas_nli
        name: gn
        split: test
      validation_anli_bzd:
        path: americas_nli
        name: bzd
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 500
                - 742
      test_anli_bzd:
        path: americas_nli
        name: bzd
        split: test
      validation_anli_hch:
        path: americas_nli
        name: hch
        split: validation
        _method_:
          shuffle:
            seed: ${seed}
          select:
            indices:
              _target_: builtins.range
              _args_:
                - 500
                - 742
      test_anli_hch:
        path: americas_nli
        name: hch
        split: test
      validation_xnli_en:
        path: xnli
        name: en
        split: validation
      test_xnli_en:
        path: xnli
        name: en
        split: test

  test:
    _datasets_:
      test_xnli_en:
        path: xnli
        name: en
        split: test
